apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudiante
  -deployment
  labels:
    app: estudiante
    -deployment
spec:
  selector:
    matchLabels:
      app: estudiante
      -deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: estudiante
        -deployment
    spec:
      containers:
        - name: estudiante
        -service
          image: josetorob/estudiante
          -service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: estudiante

                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: estudiante

                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: estudiante
  -service
  labels:
    app: estudiante
    -service
spec:
  selector:
    app: estudiante
    -deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer