server:
  port: 8081
spring:
  cloud:
    config:
      server:
        bootstrap: false
        git:
          default-label: main
          uri: https://github.com/JoseToroB/TingesoL2
          search-paths: config-data
  application:
    name: config-service
